#!/bin/bash

echo update and upgrade....
sudo apt update && sudo apt upgrade
echo Fetching Emby Server....
wget https://github.com/MediaBrowser/Emby.Releases/releases/download/4.6.4.0/emby-server-deb_4.6.4.0_amd64.deb
echo Installing Emby Server....
dpkg -i emby-server-deb_4.6.4.0_amd64.deb

echo Pre-Requisites for Webmin...
sudo apt install software-properties-common apt-transport-https wget
wget -q http://www.webmin.com/jcameron-key.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] http://download.webmin.com/download/repository sarge contrib"
echo Installing WebMin....
sudo apt update && sudo apt install webmin

echo Installing Fail2Ban.....
sudo apt install fail2ban

echo Fetching Configs....
cd /tmp
wget https://github.com/captaintofuburger/emby-configs-open/archive/refs/heads/main.zip
unzip main.zip -d /tmp


echo Stopping Fail2Ban Service...
sudo systemctl stop fail2ban
cd /var/fail2ban/
echo replacing jail.local....
rm jail.local
cp /tmp/emby-configs-open-main/jail.local /var/fail2ban/jail.local
echo adding Emby filter....
cd /var/fail2ban/filter.d/
cp /tmp/emby-configs-open-main/filter.d/emby.conf /var/fail2ban/filter.d/emby.conf
echo Adding Emby jail....
cd /var/fail2ban/jail.d/
cp /tmp/emby-configs-open-main/jail.d/emby.conf /var/fail2ban/jail.d/emby.conf
echo Configs Updated....
echo Starting Fail2Ban....
sudo systemctl start fail2ban